// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreApp struct {
	ID        uuid.UUID          `json:"id"`
	Name      []byte             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type CoreAppApiKey struct {
	ID         uuid.UUID          `json:"id"`
	AppID      uuid.UUID          `json:"app_id"`
	KeyHash    string             `json:"key_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsActive   bool               `json:"is_active"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type CoreBlacklistToken struct {
	Jti           string             `json:"jti"`
	UserID        uuid.UUID          `json:"user_id"`
	AppID         uuid.UUID          `json:"app_id"`
	Token         string             `json:"token"`
	BlacklistedAt pgtype.Timestamptz `json:"blacklisted_at"`
	Reason        *string            `json:"reason"`
}

type CoreRefreshToken struct {
	Jti       string             `json:"jti"`
	UserID    uuid.UUID          `json:"user_id"`
	AppID     uuid.UUID          `json:"app_id"`
	Token     string             `json:"token"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt time.Time          `json:"expires_at"`
}

type CoreUser struct {
	ID              uuid.UUID          `json:"id"`
	AppID           uuid.UUID          `json:"app_id"`
	Name            string             `json:"name"`
	Email           string             `json:"email"`
	IsEmailVerified bool               `json:"is_email_verified"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CoreUserAuthProvider struct {
	UserID         uuid.UUID          `json:"user_id"`
	AppID          uuid.UUID          `json:"app_id"`
	Provider       string             `json:"provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	Password       *string            `json:"password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
