// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAllApps(ctx context.Context) ([]GetAllAppsRow, error)
	GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error)
	GetAllUsersByAppID(ctx context.Context, appID uuid.UUID) ([]GetAllUsersByAppIDRow, error)
	GetAppByID(ctx context.Context, id uuid.UUID) (CoreApp, error)
	GetAppUserByID(ctx context.Context, arg GetAppUserByIDParams) (GetAppUserByIDRow, error)
	GetRefreshTokenByJTI(ctx context.Context, arg GetRefreshTokenByJTIParams) (GetRefreshTokenByJTIRow, error)
	GetUserActiveRefreshTokensByJTI(ctx context.Context, arg GetUserActiveRefreshTokensByJTIParams) ([]CoreRefreshToken, error)
	GetUserActiveRefreshTokensByUserID(ctx context.Context, arg GetUserActiveRefreshTokensByUserIDParams) ([]CoreRefreshToken, error)
	GetUserAuthenticationByProvider(ctx context.Context, arg GetUserAuthenticationByProviderParams) (CoreUserAuthProvider, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (CoreUser, error)
	LockAppForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	RevokeActiveAppApiKeys(ctx context.Context, arg RevokeActiveAppApiKeysParams) (int64, error)
	RevokeRefreshTokens(ctx context.Context, arg RevokeRefreshTokensParams) error
	RevokeResetPasswordToken(ctx context.Context, arg RevokeResetPasswordTokenParams) error
	StoreApp(ctx context.Context, arg StoreAppParams) error
	StoreAppApiKey(ctx context.Context, arg StoreAppApiKeyParams) error
	StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error
	StoreResetPasswordToken(ctx context.Context, arg StoreResetPasswordTokenParams) error
	StoreUser(ctx context.Context, arg StoreUserParams) error
	StoreUserAuthProvider(ctx context.Context, arg StoreUserAuthProviderParams) error
}

var _ Querier = (*Queries)(nil)
